name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deploy_to_gce:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v2'
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '//iam.googleapis.com/projects/899583565969/locations/global/workloadIdentityPools/kimwipes-github-action/providers/github'
        service_account: 'github-action@kimwipes.iam.gserviceaccount.com'
    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: 'kimwipes'
        zone: 'us-west1-b'
        ssh_private_key: '${{ secrets.GCE_SSH_PRIVATE_KEY }}'
        command: |-
          cd /home/oji/kimwipes
          git pull origin main
